
default: &default
  adapter: postgresql
  encoding: unicode
  username: danielc
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mtg_champs

test:
  <<: *default
  database: mtg_champs_test

production:
  <<: *default
  database: mtg_champs_production
  username: mtg_champs
  password: <%= ENV["MTG_CHAMPS_DATABASE_PASSWORD"] %>
