
default: &default
  adapter: postgresql
  encoding: unicode
  username: danielc
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mtg_champs

test:
  <<: *default
  database: mtg_champs_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
